default:
  image: node:16

build:
  stage: build

  variables:
    REACT_APP_SITE_TITLE: 哈尔滨工业大学开源镜像站
    REACT_APP_ORG_NAME: 哈尔滨工业大学Linux用户协会
    REACT_APP_ORG_LINK: https://github.com/hitlug
    REACT_APP_SPONSOR_NAME: 哈尔滨工业大学网络与信息中心
    GENERATE_SOURCEMAP: "false"

  cache:
    - key:
        files:
          - yarn.lock
      paths:
        - .yarn-cache/

  script:
    - yarn install --cache-folder .yarn-cache
    - yarn build

  artifacts:
    paths:
      - build
