name: Build

on: [push, pull_request]

jobs:
  build:
    name: Page Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          check-latest: true
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install Node.js dependencies
        run: yarn install
      - name: Page Build
        env:
          REACT_APP_SITE_TITLE: 哈尔滨工业大学开源镜像站
          REACT_APP_ORG_NAME: 哈尔滨工业大学Linux用户协会
          REACT_APP_ORG_LINK: https://github.com/hitlug
          REACT_APP_SPONSOR_NAME: 哈尔滨工业大学网络与信息中心
          GENERATE_SOURCEMAP: false
        run: yarn build
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Production Build
          path: build
  buildsz:
    name: Page Build(深圳)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          check-latest: true
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install Node.js dependencies
        run: yarn install
      - name: Page Build
        env:
          REACT_APP_SITE_TITLE: 哈尔滨工业大学(深圳)开源镜像站
          REACT_APP_ORG_NAME: 哈尔滨工业大学(深圳)计算机研究协会
          REACT_APP_ORG_LINK: https://github.com/hitszcra
          REACT_APP_SPONSOR_NAME: 哈尔滨工业大学(深圳)实验与创新实践中心
          GENERATE_SOURCEMAP: false
        run: yarn build
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Production Build(深圳)
          path: build
